# Generated by Django 3.2 on 2021-05-01 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.ManyToManyField(related_name='completed', to='series.WebSeries')),
                ('favorites', models.ManyToManyField(related_name='favorites', to='series.WebSeries')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='core.profileimage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(related_name='watched', to='series.WebSeries')),
            ],
        ),
    ]
