# Generated by Django 3.2 on 2021-05-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ManyToManyField(related_name='series', to='series.WebSeries'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.viewer'),
        ),
    ]
