# Generated by Django 3.2 on 2021-05-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesimage',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
