# Generated by Django 3.2 on 2021-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('series', '0002_alter_webseries_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries',
            name='carousel_images',
        ),
        migrations.AddField(
            model_name='webseries',
            name='carousel_images',
            field=models.ManyToManyField(blank=True, related_name='carousel_images', to='core.SeriesImage'),
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='webseries',
            name='cover_image',
            field=models.ManyToManyField(blank=True, related_name='cover_image', to='core.SeriesImage'),
        ),
    ]
